# Site settings
title: Willow Cheng
subtitle: Craftor’s journey
email: willowcheng@icloud.com
description: The warm space to host Willow Cheng's blog and portfolio, which are made by :heart:.
baseurl: ""
url: "https://willowcheng.github.io"
author: Willow Cheng
city: Toronto
state: Ontario
country: Canada
phone: +1 (613)261-6094

# Site settings in Chinese
zh:
  title: 程柳
  subtitle: 我们像只野马一样在城市里流淌
  description: 这里寄宿着博客和我的个人作品 :heart:。
  city: 多伦多
  state: 安大略省
  country: 加拿大
  phone: +86 186-1578-1919

# Custom collections
collections:
  projects:
    output: true
  posts:
    output: true

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-count: 20

# Social settings
github_url: https://github.com/willowcheng
linkedin_url: https://www.linkedin.com/in/willowcheng
instagram_url: https://www.instagram.com/willowcheng
flickr_url: https://www.flickr.com/people/willowcheng
codepen_url: http://codepen.io/willowcheng
pinterest_url: https://www.pinterest.com/willowcheng/

# Dependencies
markdown: kramdown

# Permalink
permalink: pretty

# Plugin: jekyll-seo-tag
twitter:
  username: willow_cheng

# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:

sass:
  style: :compressed

cdn:
  fontawesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css

# Misc
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor/bundle
