# Site settings
title: Willow Cheng
subtitle: Craftor’s journey
email: hi@willowcheng.com
baseurl: ""
url: "https://willowcheng.com"
author: Willow Cheng
city: Toronto
state: Ontario
country: Canada

# Site settings in Chinese
zh:
  title: 程柳
  subtitle: 我们像只野马一样在城市里流淌
  city: 多伦多
  state: 安大略省
  country: 加拿大

# Custom collections
collections:
  projects:
    output: true
  posts:
    output: true

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-count: 20

# Social settings
github_url: https://github.com/willowcheng
linkedin_url: https://linkedin.com/in/willowcheng
instagram_url: https://instagram.com/willowcheng
soundcloud_url: https://soundcloud.com/willowcheng
codepen_url: https://codepen.io/willowcheng
facebook_url: https://facebook.com/willowcheng

# Dependencies
markdown: kramdown

# Permalink
permalink: pretty

# Plugin: jekyll-seo-tag
twitter:
  username: willow_cheng

social:
  name: Willow Cheng
  links:
    - https://github.com/willowcheng
    - https://linkedin.com/in/willowcheng
    - https://instagram.com/willowcheng
    - https://soundcloud.com/willowcheng
    - https://codepen.io/willowcheng
    - https://facebook.com/willowcheng
    - https://twitter.com/willow_cheng
    - https://medium.com/@willowcheng
    - https://vimeo.com/willowcheng
    - https://behance.net/willowcheng
    - https://unsplash.com/@willowcheng
    - https://pinterest.com/willowcheng

# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/img/favicon.png

sass:
  style: :compressed

cdn:
  fontawesome: https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css

# Misc
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor/bundle
